name: Nightly Grant Scrape

on:
  # 09:00 UTC = 02:00 AM Pacific Standard / 03:00 AM Pacific Daylight
  schedule:
    - cron:  '0 9 * * *'
  workflow_dispatch:      # manual run button

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scrape_grants.py

